# Generated by Django 2.0.7 on 2018-08-10 17:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currency', models.CharField(choices=[('REV', 'REV'), ('USD', 'USD'), ('ETH', 'ETH'), ('BTC', 'BTC'), ('USDT', 'USDT')], default='REV', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manufacturer', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('state', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Trim',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trim', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_plate', models.CharField(max_length=7)),
                ('vin', models.CharField(max_length=17)),
                ('year', models.CharField(max_length=4)),
                ('mileage', models.PositiveIntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('num_doors', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(6)])),
                ('num_cylinders', models.SmallIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)])),
                ('ac_front', models.BooleanField()),
                ('ac_rear', models.BooleanField()),
                ('cruise_control', models.BooleanField()),
                ('navigation', models.BooleanField()),
                ('power_locks', models.BooleanField()),
                ('power_steering', models.BooleanField()),
                ('keyless_entry', models.BooleanField()),
                ('integrated_phone', models.BooleanField()),
                ('airbag_driver', models.BooleanField()),
                ('airbag_passenger', models.BooleanField()),
                ('arbag_side', models.BooleanField()),
                ('antilock_brakes', models.BooleanField()),
                ('fog_lights', models.BooleanField()),
                ('rear_window_defrost', models.BooleanField()),
                ('rear_window_wiper', models.BooleanField()),
                ('tinted_glass', models.BooleanField()),
                ('am_fm_stereo', models.BooleanField()),
                ('cd_player', models.BooleanField()),
                ('alloy_wheels', models.BooleanField()),
                ('dvd_system', models.BooleanField()),
                ('sun_roof', models.BooleanField()),
                ('power_windows', models.BooleanField()),
                ('premium_sound_system', models.BooleanField()),
                ('security_alarm', models.BooleanField()),
                ('third_row_seats', models.BooleanField()),
                ('tow_package', models.BooleanField()),
                ('body_style', models.CharField(choices=[('CON', 'Convertible'), ('COU', 'Coupe'), ('HAT', 'Hatchback'), ('SED', 'Sedan'), ('SUV', 'SUV')], default='COU', max_length=3)),
                ('listing_plan_choice', models.CharField(choices=[('S', 'Standard'), ('P', 'Platinum'), ('C', 'Centurion')], default='C', max_length=1)),
                ('transmissions', models.CharField(choices=[('M', 'Manual'), ('A', 'Automattic'), ('C', 'CVT')], default='A', max_length=1)),
                ('interior_color', models.CharField(choices=[('BEI', 'Beige/Tan'), ('BLK', 'Black'), ('BLU', 'Blue'), ('BRN', 'Brown'), ('GLD', 'Gold'), ('GRY', 'Grey'), ('GRN', 'Green'), ('ORG', 'Orange'), ('PNK', 'Pink'), ('PPL', 'Purple'), ('RED', 'Red'), ('SVR', 'Silver'), ('WHT', 'White'), ('YLO', 'Yellow')], default='BLK', max_length=3)),
                ('exterior_color', models.CharField(choices=[('BEI', 'Beige/Tan'), ('BLK', 'Black'), ('BLU', 'Blue'), ('BRN', 'Brown'), ('GLD', 'Gold'), ('GRY', 'Grey'), ('GRN', 'Green'), ('ORG', 'Orange'), ('PNK', 'Pink'), ('PPL', 'Purple'), ('RED', 'Red'), ('SVR', 'Silver'), ('WHT', 'White'), ('YLO', 'Yellow')], default='BLK', max_length=3)),
                ('fueltypes', models.CharField(choices=[('CNG', 'Compressed Natural Gas'), ('DIE', 'Diesel'), ('E85', 'E85 Flex Fuel'), ('ELE', 'Electric'), ('GAS', 'Gasoline'), ('HYB', 'Hybrid')], default='GAS', max_length=3)),
                ('drivetypes', models.CharField(choices=[('2', '2WD'), ('4', '4WD'), ('A', 'AWD'), ('F', 'FWD'), ('R', 'RWD')], default='2', max_length=1)),
                ('image', models.FileField(blank=True, null=True, upload_to='')),
                ('height_field', models.IntegerField(default=0)),
                ('width_field', models.IntegerField(default=0)),
                ('vehicle_history', models.URLField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('currency', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.Currency')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.Manufacturer')),
                ('state', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.State')),
            ],
        ),
        migrations.CreateModel(
            name='VModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vmodel', models.CharField(max_length=50)),
                ('trim', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.Trim')),
            ],
        ),
        migrations.AddField(
            model_name='manufacturer',
            name='vmodel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='vehicles.VModel'),
        ),
    ]
